import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { links } from "../data/data";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mobile App Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link href="/" className={styles.logo}>
          <a>
            <Image width="32" height="32" src="/Logo.png" />
          </a>
        </Link>
        <nav className={styles.nav}>
          <ul className={styles.menu}>
            {links.map(link => (
              <li className={styles.menu__item}>
                <Link href="/" className={styles.menu__link}>
                  <a>{link}</a>
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </header>
    </div>
  );
}
